name: ks33requests-dev
channels:
  - conda-forge
dependencies:
  - requests
  - lxml
  - jupyter
  - python-dotenv
  - twine
  - coverage
  - codecov
  - sphinx
  - recommonmark
  - pandoc
  - nbsphinx
  - pip:
      - generateDS
