# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

references:
  test_steps: &test_steps
    steps:
      - checkout
      - run:
          name: Install develop requirements
          command: sudo pip install -r requires/dev.txt
      - run:
          name: Run test with coverage
          command: |
            # run unit test cases with coverage
            coverage run setup.py test
            # generate an XML report of coverage results
            coverage xml
            # upload test report to Code Climate using `after-build`
            codecov -f coverage.xml

  publish_steps: &publish_steps
    steps:
      - checkout
      - run:
          name: Install additional pip dependencies
          command: sudo pip install wheel twine
      - run:
          name: Build and upload dist
          command: |
            python setup.py sdist bdist_wheel
            twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

jobs:
  test:
    docker:
      - image: circleci/python:3
    <<: *test_steps

  publish:
    docker:
      - image: circleci/python:3
    <<: *publish_steps

workflows:
  version: 2
  test_publish_workflow:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(\.?(a|b|rc|post)[0-9]+(\.[0-9]+)*)?/
            branches:
              ignore: /.*/
