# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2

references:
  tests_steps: &tests_steps
    steps:
      - checkout
      - run:
          name: Install develop requires
          command: sudo pip install -r requires/dev.txt
      - run:
          name: Run coverage tests
          command: |
            # run unit test cases with coverage
            coverage run setup.py test
            # generate an XML report of coverage results
            coverage xml
            # upload test report to Code Climate using `after-build`
            codecov -f coverage.xml

  deploy_steps: &deploy_steps
    steps:
      - checkout
      - run:
          name: Install additional pip dependencies
          command: sudo pip install wheel twine
      - run:
          name: Build and upload dist
          command: |
            python setup.py sdist bdist_wheel
            twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*

jobs:
  test-python3:
    docker:
      - image: circleci/python:3
    <<: *tests_steps

  deploy:
    docker:
      - image: circleci/python
    <<: *deploy_steps

workflows:
  version: 2
  test-and-deploy: # name of your workflow
    jobs:
      - test-python3
      - deploy:
          requires:
            - test-python3
          filters:
            tags:
              only: /^\d+(\.\d+)*(\.?(a|b|rc|post)\d+(\.\d+)*)?/
            branches:
              ignore: /.*/
